# contrib-wide Makefile include file, generated automatically with
# ./configure --fastjet-config=/direct/star+u/robotmon/fastjet1/fastjet-3.3.0/fastjet-config --prefix=/direct/star+u/robotmon/fastjet1/fastjet_install CXXFLAGS=-m32 -fPIC -fno-inline CFLAGS=-m32 -fPIC -fno-inline LDFLAGS=-m32
CXXFLAGS=-m32 -fPIC -fno-inline
CFLAGS=-m32 -fPIC -fno-inline
LDFLAGS=-m32
FASTJETCONFIG=/direct/star+u/robotmon/fastjet1/fastjet-3.3.0/fastjet-config
PREFIX=/direct/star+u/robotmon/fastjet1/fastjet_install
install_script = $(SHELL) ../utils/install-sh
check_script = ../utils/check.sh
